SIM ?= verilator

TOPLEVEL_LANG = verilog
VERILOG_SOURCES = ../../rtl/compute_fabric/dummy_accel.sv
TOPLEVEL = dummy_accel
MODULE = tb_dummy_accel_cocotb

include $(shell cocotb-config --makefiles)/Makefile.sim
